### ISSUE TITLE
The code that detects the repository is fragile

### ISSUE THREAD

**Issue by fabpot** [lyrixx/GithubComment#9]
The current assumes that the first remote is the one for Github, but that's not always the case as you can have more than one remote (like for me :)). We should iterate over all remotes instead and look for the `origin` remote and/or the first one on Github.

**Comment by lyrixx** [comment]
Hello Fabien. 

Sorry I missed your issue.

You can used `organization` and `repository` [options](https://github.com/lyrixx/GithubComment/blob/master/GithubComment/Command/CommentCommand.php#L31-L32).
